### ISSUE TITLE
todo: verification

### ISSUE THREAD

**Issue by pazos** [flathub/rocks.koreader.KOReader#34]
After #32, #33

Docs: https://docs.flathub.org/docs/for-app-authors/verification/

Thoughts?

@proletarius101 @Frenzie

**Comment by Frenzie** [comment]
Putting an extra file in https://github.com/koreader/koreader.github.io/ doesn't really seem any different than putting a release artifact on https://github.com/koreader/koreader but if that's desirable for some reason it's fine by me.

**Comment by pazos** [comment]
> Putting an extra file in https://github.com/koreader/koreader.github.io/ doesn't really seem any different than putting a release artifact on https://github.com/koreader/koreader but if that's desirable for some reason it's fine by me.

It isn't the same.
It is like F-Droid: an external store that has its own build pipeline. But fdroid is centralized and there's no way to have different KOReader versions in there, while in Flathub each dev can submit an app as long as the app id differs.

Currently there's only one, backed by this repo, that has the proper app id (rocks.koreader.KOReader) and was provided as a friendly contribution. So by verifying this one we at least aknowledge it exists and meets certain criteria for publishing.

The "unverified/verified" badge is available on https://flathub.org/apps/rocks.koreader.KOReader and potentially on app stores that support flatpak.

**Comment by Frenzie** [comment]
It's now verified and complaining about some things.
![image](https://github.com/flathub/rocks.koreader.KOReader/assets/202757/44b9fc89-66c4-4588-80b9-0bcc97a8b515)

**Comment by pazos** [comment]
> It's now verified and complaining about some things.

1. Brand colors:

That's easy. https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#brand-colors

white for light mode and a dark color that's ok with the logo. Maybe https://encycolorpedia.es/303030?


2. App icon:

https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-icon

square svg with more padding?


3. Summary:

**Document viewer**

¿?

And adjust a bit the description. I'm not a fan of current fdroid metadata either: https://f-droid.org/en/packages/org.koreader.launcher.fdroid/

Fdroid metadata supports translations, so maybe we could come up with generic metadata for stores and pushing the changes to https://github.com/koreader/koreader/tree/master/metadata

Screenshots for fdroid are also picked from images/phoneScreenshots.  We can add images/computerScreenshots and push the same content following https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#screenshots

**Comment by Frenzie** [comment]
> Document viewer

I guess so

**Comment by pazos** [comment]
> app icon

something like
 
![koreader-square](https://github.com/flathub/rocks.koreader.KOReader/assets/975883/65fe9e4d-816c-4106-bee7-a15ba3f0f328)

??

**Comment by Frenzie** [comment]
I didn't check what it says about it. That's supposed to mean cutting off the corners a little like on Android? Should be fine.
