### ISSUE TITLE
Update to 2024.11

### ISSUE THREAD

**Issue by shimeike** [flathub/rocks.koreader.KOReader#53]
```diff
--- #<buffer rocks.koreader.KOReader.yml>
+++ #<buffer rocks.koreader.KOReader.yml>
@@ -34,8 +34,8 @@
     sources:
       - type: file
         only-arches: [x86_64]
-        url: https://github.com/koreader/koreader/releases/download/v2024.07/koreader-linux-x86_64-v2024.07.tar.xz
-        sha256: b0f0ed8dd48e0adbf3b663f034e08791de8945a7788c97de476accb9648cfab6
+        url: https://github.com/koreader/koreader/releases/download/v2024.11/koreader-linux-x86_64-v2024.11.tar.xz
+        sha256: a6f6ccb07e30f701a5e2d27bdb7f4d064b55c7169bee556dbd4da0090b8056e8
         dest-filename: koreader.tar.xz
         x-checker-data:
           type: json
@@ -47,8 +47,8 @@
 
       - type: file
         only-arches: [aarch64]
-        url: https://github.com/koreader/koreader/releases/download/v2024.07/koreader-linux-aarch64-v2024.07.tar.xz
-        sha256: 0efde1a99d87daf33fc2dfbcedcaba997db8e3f8cdf48b113a9192aa2463d31b
+        url: https://github.com/koreader/koreader/releases/download/v2024.11/koreader-linux-aarch64-v2024.11.tar.xz
+        sha256: 993d5d961fa05438b347c06a826fabf49c9667751434aec5f99c8ed68ba4301b
         dest-filename: koreader.tar.xz
         x-checker-data:
           type: json
```

**Comment by Frenzie** [comment]
Isn't flathubbot supposed to do that automatically @pazos @proletarius101?

**Comment by pazos** [comment]
@Frenzie: not an issue here.

https://github.com/flathub-infra/flatpak-builder-lint/blob/master/flatpak_builder_lint/staticfiles/exceptions.json contains

```
    "rocks.koreader.KOReader": {
        "flathub-json-automerge-enabled": "Predates the linter rule"
    },
```

So the flathub bot should be working ¿?

Refs:
https://docs.flathub.org/docs/for-app-authors/external-data-checker/#automatically-merge-prs
and https://docs.flathub.org/docs/for-app-authors/linter#flathub-json-automerge-enabled

No real idea

**Comment by shimeike** [comment]
Is it possible to trigger a manual build at https://buildbot.flathub.org  and/or do you see any errors there for your automatic build? (The interface there does not allow an unprivileged user to see anything other than latest build statuses.)

flatpak has been by far the most convenient means to keep a packaged and up-to-date version of koreader installed on Linux, so it would be great if this package format could continue! Appreciate the work on this awesome application!

**Comment by Frenzie** [comment]
What I mean is that it simply opens a PR which itself triggers a build: https://github.com/flathub/rocks.koreader.KOReader/pull/47

**Comment by Frenzie** [comment]
Incidentally if it happens again in the future a PR could've already been merged last week. ^_^

**Comment by shimeike** [comment]
Awesome - thanks!

I guess we'll see on next KOReader release, but it does seem no-body understands why automated PR did not get created for 2024.11 ...
